version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - REDIS_DNS=redis  # Use the service name "redis" as the hostname
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: