apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1  # You can adjust this as needed
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379