apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/impostermp/simple-fortune-cookie-backend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
