apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/impostermp/simple-fortune-cookie-frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_DNS
              value: "backend"