apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/impostermp/simple-fortune-cookie-frontend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: BACKEND_DNS
            value: backend