name: DEC_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    # Steps represent a sequence of tasks that will be executed as part of the job
  
  jobs:

    Testing:
      runs-on: ubuntu-latest
      needs: [Build]
      steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: . 
      - name: Test frontend
        run: cd frontend && go test
        #ny test