name: DEVELOPMENT_CI
on:
  push:
    branches: 
    - "feature/issue#*" 
  

jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Upload Repo
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .

  Build:
    runs-on: ubuntu-latest
    needs: [Clone-down]
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: code
        path: . 
    - name: Build Frontend
      run: cd frontend && go build frontend
    - name: Build Backend
      run: cd backend && go build backend 
    - name: Upload Repo
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .
      

  Tests:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: code
        path: . 
    - name: Test frontend
      run: cd frontend && go test
